version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: dj_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ".env"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=mysql://dj_user:userpassword@db/mydatabase
      - REDIS_URL=redis://redis:6379

  celery:
    build: .
    command: celery -A core worker --pool=solo -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=mysql://dj_user:userpassword@db/mydatabase
      - REDIS_URL=redis://redis:6379

volumes:
  db_data: