
services:
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ".env"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - main_net
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://radwan:radwan123@db:5432/master
      - REDIS_URL=redis://redis:6379
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - main_net

  redis:
    image: redis:latest
    restart: always
    networks:
      - main_net


  celery:
    build: .
    command: celery -A core worker --pool=solo -l info
    networks:
      - main_net
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://radwan:radwan123@db:5432/master
      - CELERY_BROKER_URL = "redis://redis:6379/0"


volumes:
  pgdata2:

networks:
  main_net:
    driver: bridge